@echo off
SETLOCAL EnableExtensions DisableDelayedExpansion

if exist build rmdir /s /q build
mkdir build
cd build

cmake %SRC_DIR% ^
    -DCMAKE_CXX_FLAGS="%CMAKE_CXX_FLAGS% /DWIN32 /bigobj /wd4996 /wd4101" ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_VERBOSE_MAKEFILE=ON ^
    -DBUILD_AZURE_KINECT=OFF ^
    -DBUILD_CUDA_MODULE=OFF ^
    -DBUILD_COMMON_CUDA_ARCHS=OFF ^
    -DBUILD_CACHED_CUDA_MANAGER=OFF ^
    -DBUILD_EXAMPLES=OFF ^
    -DBUILD_ISPC_MODULE=OFF ^
    -DBUILD_GUI=ON ^
    -DBUILD_LIBREALSENSE=OFF ^
    -DBUILD_PYTORCH_OPS=OFF ^
    -DBUILD_REALSENSE=OFF ^
    -DBUILD_SHARED_LIBS=ON ^
    -DBUILD_TENSORFLOW_OPS=OFF ^
    -DBUILD_WEBRTC=OFF ^
    -DENABLE_HEADLESS_RENDERING=OFF ^
    -DBUILD_JUPYTER_EXTENSION=OFF ^
    -DOPEN3D_USE_ONEAPI_PACKAGES=OFF ^
    -DUSE_BLAS=OFF ^
    -DUSE_SYSTEM_ASSIMP=ON ^
    -DUSE_SYSTEM_BLAS=ON ^
    -DUSE_SYSTEM_CURL=ON ^
    -DUSE_SYSTEM_EIGEN3=ON ^
    -DUSE_SYSTEM_EMBREE=ON ^
    -DUSE_SYSTEM_FMT=ON ^
    -DUSE_SYSTEM_GLEW=ON ^
    -DUSE_SYSTEM_GLFW=ON ^
    -DUSE_SYSTEM_GOOGLETEST=ON ^
    -DUSE_SYSTEM_IMGUI=OFF ^
    -DUSE_SYSTEM_JPEG=ON ^
    -DUSE_SYSTEM_JSONCPP=ON ^
    -DUSE_SYSTEM_LIBLZF=ON ^
    -DUSE_SYSTEM_LIBREALSENSE=OFF ^
    -DUSE_SYSTEM_MSGPACK=ON ^
    -DUSE_SYSTEM_NANOFLANN=ON ^
    -DUSE_SYSTEM_OPENSSL=OFF ^
    -DUSE_SYSTEM_PNG=ON ^
    -DUSE_SYSTEM_PYBIND11=ON ^
    -DUSE_SYSTEM_QHULLCPP=ON ^
    -DUSE_SYSTEM_TBB=ON ^
    -DUSE_SYSTEM_TINYGLTF=OFF ^
    -DUSE_SYSTEM_TINYOBJLOADER=ON ^
    -DUSE_SYSTEM_VTK=ON ^
    -DUSE_SYSTEM_ZEROMQ=ON ^
    -DWITH_FAISS=OFF ^
    -DWITH_IPP=OFF ^
    -DPython3_EXECUTABLE=%PYTHON%
if errorlevel 1 exit 1

cmake --build . --config Release -- /m:%CPU_COUNT%
if errorlevel 1 exit 1

cmake --build . --config Release --target install
if errorlevel 1 exit 1

cmake --build . --config Release --target install-pip-package
if errorlevel 1 exit 1

set "ALIAS_METADATA_DIR=%SP_DIR%\open3d_cpu-%PKG_VERSION%.dist-info"
if exist "%ALIAS_METADATA_DIR%" exit 1
mkdir "%ALIAS_METADATA_DIR%"
(
    echo Metadata-Version: 2.1
    echo Name: open3d-cpu
    echo Version: %PKG_VERSION%
) >"%ALIAS_METADATA_DIR%\METADATA"
>"%ALIAS_METADATA_DIR%\INSTALLER" echo conda
