# aligned_alloc requires 10.15
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]

c_compiler_version:        # [osx]
- '18'                     # [osx]
cxx_compiler_version:      # [osx]
- '18'                     # [osx]
