c_compiler_version:        # [osx]
- '18'                     # [osx]
cxx_compiler_version:      # [osx]
- '18'                     # [osx]

c_compiler:                # [aarch64]
  - clang                  # [aarch64]
c_compiler_version:        # [aarch64]
  - 17                     # [aarch64]
cxx_compiler:              # [aarch64]
  - clangxx                # [aarch64]
cxx_compiler_version:      # [aarch64]
  - 17                     # [aarch64]
