# aligned_alloc requires 10.15
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]

c_stdlib_version:          # [linux]
  - "2.28"                 # [linux]

c_compiler:                # [aarch64]
  - clang                  # [aarch64]
c_compiler_version:        # [aarch64]
  - 17                     # [aarch64]
cxx_compiler:              # [aarch64]
  - clangxx                # [aarch64]
cxx_compiler_version:      # [aarch64]
  - 17                     # [aarch64]
