{% set name = "Open3D" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isl-org/Open3D/archive/v{{ version }}.tar.gz
  sha256: 524ddeb7dc8aaed6dc5b272415df0c8ffcf7eff0816a84cfbdee56cdd6d3587a
  patches:
    - fix-tbb.patch
    - fix-unzip.patch
    - fix-curl.patch
    - fix-error.patch
    - fix-find-imgui.patch
    - fix-find-embree.patch
    - fix-cross-compile-shader.patch  # [build_platform != target_platform]
    - fix-crypto.patch  # [osx]
    # https://github.com/isl-org/Open3D/pull/6783 and https://github.com/isl-org/Open3D/pull/6969
    - fix-fmt11-support.patch

build:
  number: 11
  skip: True  # [win]
  ignore_run_exports_from:
    - libcblas
    - minizip
    - msgpack-c
    - msgpack-cxx
  run_exports:
    - {{ pin_subpackage('open3d', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - llvm-openmp                            # [osx]
    - libgomp                                # [linux]
    - python                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - qt6-main                               # [build_platform != target_platform and not ppc64le]
    - libcxx 17                              # [osx]
  host:
    - libgl-devel                        # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxcb                        # [linux]
    - setuptools
    - python
    - pip
    - assimp
    - libzlib
    - eigen
    - embree 3.*
    - glew
    - glfw
    - fmt
    - libjpeg-turbo
    - gmock
    - jsoncpp
    - zeromq
    - cppzmq
    - msgpack-c
    - msgpack-cxx
    - minizip
    - vtk * qt*
    # We have also a vanilla dependency of vtk without pins so that conda-smithy correctly sets the
    # pin from conda-forge-pinnings
    - vtk
    - libpng
    - pybind11
    - qhull
    - qhull-static
    - tinyobjloader
    - libcblas
    - liblapacke
    - libboost-headers
    - nanoflann
    - liblzf
    - libcurl
    - openssl  # [osx]
    # TODO: Consider for the future
    # - libidn2  # [osx]
    # - imgui      # Not used currently as we are not building the GUI
    # - tinygltf   # TODO: Does not export cmake config in conda-forge; see https://github.com/conda-forge/tinygltf-feedstock/issues/24
    # - tbb-devel  # conda-forge version too new; no oneTBB support yet; see https://github.com/isl-org/Open3D/issues/6544
  run:
    - numpy
    - python
    - plotly
    - dash
    - vtk-base * qt*

test:
  imports:
    - open3d
  commands:
    - open3d --help

about:
  home: http://www.open3d.org/
  summary: Open-source library that supports rapid development of software that deals with 3D data.
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_TBB
    - 3rdparty/uvatlas/LICENSE_directxheaders
    - 3rdparty/uvatlas/LICENSE_directxmath
    - 3rdparty/uvatlas/LICENSE_uvatlas
    - 3rdparty/parallelstl/LICENSE
    - 3rdparty/possionrecon/LICENSE
    - 3rdparty/rply/LICENSE
    - 3rdparty/tinyfiledialogs/LICENSE
    - 3rdparty/tinygltf/LICENSE
  dev_url: https://github.com/isl-org/Open3D

extra:
  recipe-maintainers:
    - goanpeca
    - Tobias-Fischer
