build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: alma8
  linux_aarch64: alma8
test: native_and_emulated
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: "C:\bld"
      MINIFORGE_HOME: "C:\Miniforge"
